{
 "title": "HomeWizard APIv2",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Power (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(total_power_import_kwh{job=\"homewizard-apiv2\", api_version=\"v1\", product_type=\"HWE-P1\"}[$__rate_interval])*3600000",
     "legendFormat": "{{instance}}_import"
    },
    {
     "expr": "-rate(total_power_export_kwh{job=\"homewizard-apiv2\", api_version=\"v1\", product_type=\"HWE-P1\"}[$__rate_interval])*3600000",
     "legendFormat": "{{instance}}_export"
    },
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EnergySockets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "active_power_w{job=\"homewizard-apiv2\", api_version=\"v1\", product_type=\"HWE-SKT\"}",
     "legendFormat": "{{instance}}_power_w"
    }
   ]
  },
  {
   "title": "Batteries (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(energy_import_kwh{job=\"homewizard-apiv2\", api_version=\"v2\", product_type=\"HWE-BAT\"}[$__rate_interval])*3600000",
     "legendFormat": "{{instance}}_import"
    },
    {
     "expr": "-rate(energy_export_kwh{job=\"homewizard-apiv2\", api_version=\"v2\", product_type=\"HWE-BAT\"}[$__rate_interval])*3600000",
     "legendFormat": "{{instance}}_export"
    }
   ]
  },
  {
   "title": "Batteries (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "state_of_charge_pct{job=\"homewizard-apiv2\", api_version=\"v2\"} / scalar(count(state_of_charge_pct{job=\"homewizard-apiv2\", api_version=\"v2\"}))",
     "legendFormat": "{{instance}}_charge"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(total_gas_m3{job=\"homewizard-apiv2\", api_version=\"v1\", product_type=\"HWE-P1\"}[$__rate_interval])",
     "legendFormat": "{{instance}}_m3"
    }
   ]
  },
  {
   "title": "Water",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(total_liter_m3{job=\"homewizard-apiv2\", api_version=\"v1\", product_type=\"HWE-WTR\"}[$__rate_interval])*100000",
     "legendFormat": "{{instance}}_liter"
    }
   ]
  }
 ]
}